name: khidmeti_users
description: Application mobile pour les utilisateurs de KHIDMETI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10
  
  # UI & Navigation
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  
  # Maps & Location
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # State Management
  provider: ^6.1.1
  
  # Image & Media
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  
  # Utils
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  permission_handler: ^11.1.0
  connectivity_plus: ^5.0.2
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # UI Components
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: Paytone One
      fonts:
        - asset: assets/fonts/PaytoneOne-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/