name: worker_app
description: Worker Flutter app for Khidmeti
publish_to: 'none'
version: 0.1.0+1

environment:
	 sdk: '>=3.3.0 <4.0.0'

dependencies:
	 flutter:
		 sdk: flutter
	 cupertino_icons: ^1.0.6
	 provider: ^6.0.5
	 firebase_core: ^2.25.5
	 firebase_auth: ^4.17.9
	 cloud_firestore: ^4.15.8
	 firebase_messaging: ^14.7.19
	 firebase_storage: ^11.6.9
	 image_picker: ^1.1.1
	 google_mlkit_text_recognition: ^0.13.0
	 google_mlkit_face_detection: ^0.11.0
	 http: ^1.2.1


dev_dependencies:
	 flutter_test:
		 sdk: flutter
	 flutter_lints: ^3.0.1

flutter:
	 uses-material-design: true
}