name: khidmeti_worker
description: Khidmeti Worker App (Professional Paytone One design)
version: 0.0.1+1
publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^11.0.0
  permission_handler: ^11.3.1
  intl: ^0.19.0
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.2.1
  firebase_messaging: ^15.0.3
  firebase_storage: ^13.1.2
  shared_assets:
    path: ../shared_assets

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true