name: khidmeti_workers
description: Application travailleurs Khidmeti - Gérez vos services professionnels
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Backend
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10

  # UI & Animations (Style moderne)
  lottie: ^2.7.0
  animations: ^2.0.8
  flutter_animate: ^4.2.0+1
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0

  # Maps OpenStreetMap
  flutter_map: ^6.1.0
  latlong2: ^0.8.2
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # State Management
  provider: ^6.1.1
  
  # Media & Utils  
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  http: ^1.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/
    - assets/avatars/workers/
    - assets/icons/
    - assets/images/
  
  fonts:
    - family: Paytone One
      fonts:
        - asset: assets/fonts/PaytoneOne-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700