name: client_app
description: Client Flutter app for Khidmeti
publish_to: 'none'
version: 0.1.0+1

environment:
	 sdk: '>=3.3.0 <4.0.0'

dependencies:
	 flutter:
		 sdk: flutter
	 cupertino_icons: ^1.0.6
	 provider: ^6.0.5
	 firebase_core: ^2.25.5
	 firebase_auth: ^4.17.9
	 cloud_firestore: ^4.15.8
	 firebase_storage: ^11.6.9
	 image_picker: ^1.1.1
	 flutter_map: ^6.1.0
	 latlong2: ^0.9.0
	 flutter_map_marker_cluster: ^1.2.0


dev_dependencies:
	 flutter_test:
		 sdk: flutter
	 flutter_lints: ^3.0.1

flutter:
	 uses-material-design: true