name: khidmeti_users
description: Application clients Khidmeti - Service de mise en relation avec des travailleurs
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.10
  firebase_storage: ^11.5.6
  
  # UI & Animations
  lottie: ^2.7.0
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  
  # Maps
  flutter_map: ^6.1.0
  geolocator: ^10.1.0
  latlong2: ^0.9.0
  
  # State Management
  provider: ^6.1.1
  
  # Utils
  intl: ^0.18.1
  uuid: ^4.2.1
  image_picker: ^1.0.4
  permission_handler: ^11.1.0
  
  # HTTP & Networking
  http: ^1.1.2
  connectivity_plus: ^5.0.2
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/
    - assets/avatars/users/
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: PaytoneOne
      fonts:
        - asset: assets/fonts/PaytoneOne-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700