name: khidmeti_users
description: Khidmeti Users app - Paytone One design, SOLID architecture, OpenStreetMap, Firebase.
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^10.1.0
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  firebase_messaging: ^15.1.3
  provider: ^6.1.2
  intl: ^0.19.0
  shared_preferences: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/avatars/users/
    - assets/icons/
    - assets/images/